version: "3.9"
services:
  web:
    build:
      context: ../..
      dockerfile: .docker/prod/Dockerfile
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/lssf_hts_prod
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    depends_on:
      - db
    command: >
      bash -c "
        ./bin/lssf_hts eval 'LssfHts.Release.migrate()' &&
        ./bin/server
      "
    env_file:
    - .env.prod

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lssf_hts_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  scan_server:
    image: scan_service
    ports:
      - "4001:4001"
    volumes:
      - /dev:/dev
      - /run/udev:/run/udev
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    restart: unless-stopped
volumes:
  postgres_data:
